### PR TITLE
Upgraded rally-sbt-plugin.

### PR DESCRIPTION
**Pull request by jeffmay**
@chrissalij-r @htmldoug @patrick-bohan @slustbader 

I wonder if we do a new release with this version if it will work.

### CODE REVIEW

**Comment by chrissalij-r** [comment]
Maybe. Do a local publish and see if RCU complains

**Comment by slustbader** [comment]
LGTM, although I'm skeptical.

**Comment by jeffmay** [comment]
No issues on publish local.

**Comment by patrick-bohan** [comment]
LGTM, but I'd love to see SH upgraded with this first...

**Comment by chrissalij-r** [comment]
@patrick-bohan SH didn't have an issue updating to v1.1.0 though, it was only RCU that did.

**Comment by patrick-bohan** [comment]
True, and lib-wellness-profile, since both that and RCU depend on SH.

**Comment by jeffmay** [comment]
Ok, this is worth a shot, I guess.

**Pull request merged**
